json.id recipe.id
json.title recipe.title
json.ingredients recipe.ingredients
json.prep_time recipe.prep_time
json.cook_time recipe.cook_time
json.total_time recipe.total_time
json.instructions recipe.instructions
json.created_at recipe.created_at
json.updated_at recipe.updated_at
json.image recipe.image
